"""chat messages details and llm call errors

Revision ID: 039df0832001
Revises: 41fb0c00cbdd
Create Date: 2026-10-06 09:31:49.417633
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "039df0832001"
down_revision: str | None = "41fb0c00cbdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_calls", sa.Column("error", sa.Text(), nullable=True))
    op.add_column(
        "messages",
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "details_json")
    op.drop_column("llm_calls", "error")
    # ### end Alembic commands ###
