"""paper ocr pages

Revision ID: 3bc4a4efa4dc
Revises: 83c33f68cea1
Create Date: 2026-10-06 17:26:07.122923
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3bc4a4efa4dc"
down_revision: str | None = "83c33f68cea1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column("ocr_pages_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "ocr_pages_json")
    # ### end Alembic commands ###
