"""rq fit assessment fields

Revision ID: 91bf0e26ce66
Revises: 7c2e9a41b3d8
Create Date: 2026-10-06 10:18:11.281283
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "91bf0e26ce66"
down_revision: str | None = "7c2e9a41b3d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("rq_suggestions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "projects", sa.Column("rq_suggestions_status", sa.String(length=16), nullable=True)
    )
    op.add_column("projects", sa.Column("rq_suggestions_error", sa.Text(), nullable=True))
    op.add_column(
        "research_questions",
        sa.Column("mapping_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "research_questions",
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
    )
    op.add_column("research_questions", sa.Column("error", sa.Text(), nullable=True))
    op.add_column(
        "research_questions", sa.Column("version", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("rq_assessments", sa.Column("explanation", sa.Text(), nullable=True))
    op.add_column("rq_assessments", sa.Column("rewording", sa.Text(), nullable=True))
    op.add_column(
        "rq_assessments",
        sa.Column("facts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rq_assessments",
        sa.Column("grounding_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("rq_assessments", sa.Column("explained_by", sa.String(length=16), nullable=True))
    op.add_column(
        "rq_assessments",
        sa.Column("problems_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "rq_assessments",
        "config_version",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rq_assessments",
        "config_version",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_column("rq_assessments", "problems_json")
    op.drop_column("rq_assessments", "explained_by")
    op.drop_column("rq_assessments", "grounding_json")
    op.drop_column("rq_assessments", "facts_json")
    op.drop_column("rq_assessments", "rewording")
    op.drop_column("rq_assessments", "explanation")
    op.drop_column("research_questions", "version")
    op.drop_column("research_questions", "error")
    op.drop_column("research_questions", "status")
    op.drop_column("research_questions", "mapping_json")
    op.drop_column("projects", "rq_suggestions_error")
    op.drop_column("projects", "rq_suggestions_status")
    op.drop_column("projects", "rq_suggestions_json")
    # ### end Alembic commands ###
