"""table relationships

Revision ID: 0cb66d49fc5d
Revises: a5a49f992f86
Create Date: 2026-10-06 14:13:54.473450
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0cb66d49fc5d"
down_revision: str | None = "a5a49f992f86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table_relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("left_dataset_id", sa.Integer(), nullable=False),
        sa.Column("left_column", sa.String(length=300), nullable=False),
        sa.Column("right_dataset_id", sa.Integer(), nullable=False),
        sa.Column("right_column", sa.String(length=300), nullable=False),
        sa.Column("shared_values", sa.BigInteger(), nullable=False),
        sa.Column("left_distinct", sa.BigInteger(), nullable=False),
        sa.Column("right_distinct", sa.BigInteger(), nullable=False),
        sa.Column("left_coverage", sa.Float(), nullable=False),
        sa.Column("right_coverage", sa.Float(), nullable=False),
        sa.Column("cardinality", sa.String(length=16), nullable=False),
        sa.Column("name_match", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["left_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_table_relationships_left_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_table_relationships_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["right_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_table_relationships_right_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_table_relationships")),
    )
    op.create_index(
        op.f("ix_table_relationships_left_dataset_id"),
        "table_relationships",
        ["left_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_relationships_project_id"),
        "table_relationships",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_relationships_right_dataset_id"),
        "table_relationships",
        ["right_dataset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_table_relationships_right_dataset_id"), table_name="table_relationships")
    op.drop_index(op.f("ix_table_relationships_project_id"), table_name="table_relationships")
    op.drop_index(op.f("ix_table_relationships_left_dataset_id"), table_name="table_relationships")
    op.drop_table("table_relationships")
    # ### end Alembic commands ###
