"""semantic layer fields

Revision ID: fa73786e050a
Revises: 0cb66d49fc5d
Create Date: 2026-10-06 14:30:19.496714
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fa73786e050a"
down_revision: str | None = "0cb66d49fc5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "columns", sa.Column("description_confidence", sa.String(length=8), nullable=True)
    )
    op.add_column("columns", sa.Column("pii_reason", sa.String(length=200), nullable=True))
    op.add_column("datasets", sa.Column("describe_status", sa.String(length=16), nullable=True))
    op.add_column("datasets", sa.Column("describe_error", sa.Text(), nullable=True))
    op.add_column(
        "projects", sa.Column("share_samples", sa.Boolean(), server_default="true", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "share_samples")
    op.drop_column("datasets", "describe_error")
    op.drop_column("datasets", "describe_status")
    op.drop_column("columns", "pii_reason")
    op.drop_column("columns", "description_confidence")
    # ### end Alembic commands ###
