"""reference entries

Revision ID: 24936e7c2935
Revises: 3bc4a4efa4dc
Create Date: 2026-10-06 17:29:21.229364
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "24936e7c2935"
down_revision: str | None = "3bc4a4efa4dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("cite_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("authors_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("doi", sa.String(length=300), nullable=True),
        sa.Column("files_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("paper_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_reference_entries_paper_id_papers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reference_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_entries")),
        sa.UniqueConstraint("project_id", "cite_key", name=op.f("uq_reference_entries_project_id")),
    )
    op.create_index(
        op.f("ix_reference_entries_paper_id"), "reference_entries", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_reference_entries_project_id"), "reference_entries", ["project_id"], unique=False
    )
    op.add_column("papers", sa.Column("cite_key", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "cite_key")
    op.drop_index(op.f("ix_reference_entries_project_id"), table_name="reference_entries")
    op.drop_index(op.f("ix_reference_entries_paper_id"), table_name="reference_entries")
    op.drop_table("reference_entries")
    # ### end Alembic commands ###
