"""insight runs

Revision ID: 3c430427c881
Revises: 91bf0e26ce66
Create Date: 2026-10-06 10:52:42.456625
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3c430427c881"
down_revision: str | None = "91bf0e26ce66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insight_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("planned", sa.Integer(), nullable=True),
        sa.Column("failed_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dropped_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("used_llm", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("config_version", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_insight_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_runs")),
    )
    op.create_index(
        op.f("ix_insight_runs_project_id"), "insight_runs", ["project_id"], unique=False
    )
    op.add_column("insights", sa.Column("run_id", sa.Integer(), nullable=True))
    op.add_column("insights", sa.Column("status", sa.String(length=16), nullable=True))
    op.add_column(
        "insights", sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "insights",
        sa.Column("query_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "insights",
        sa.Column("grounding_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("insights", sa.Column("written_by", sa.String(length=16), nullable=True))
    op.create_index(op.f("ix_insights_run_id"), "insights", ["run_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_insights_run_id_insight_runs"),
        "insights",
        "insight_runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_insights_run_id_insight_runs"), "insights", type_="foreignkey")
    op.drop_index(op.f("ix_insights_run_id"), table_name="insights")
    op.drop_column("insights", "written_by")
    op.drop_column("insights", "grounding_json")
    op.drop_column("insights", "query_ids_json")
    op.drop_column("insights", "spec_json")
    op.drop_column("insights", "status")
    op.drop_column("insights", "run_id")
    op.drop_index(op.f("ix_insight_runs_project_id"), table_name="insight_runs")
    op.drop_table("insight_runs")
    # ### end Alembic commands ###
